import { EXAM_DATE, norm, round, slugify, sourceList, weeksBetween, API_VERSION } from './config.mjs';

const done=s=>norm(s).includes('concluid')||norm(s).includes('finalizad')||norm(s)==='feito';
const started=s=>done(s)||norm(s).includes('andamento')||norm(s).includes('parcial');
const sortDate=(a,b)=>String(a.date||'').localeCompare(String(b.date||''))||String(a.pe||a.rd||'').localeCompare(String(b.pe||b.rd||''));
const accuracy=x=>x.acertos!=null&&x.attempted>0?round(x.acertos/x.attempted*100):null;
const meta=d=>({snapshotDate:d,examDate:EXAM_DATE,syncTimes:['00h50','06h50','12h50','18h50'],version:'21.0',sources:sourceList()});
function quality(cs){const out=[];for(const x of cs){if(x.meta>0&&x.attempted>0&&x.meta!==x.attempted)out.push({severity:'high',pe:x.pe,title:'Meta e distribuição não fecham',detail:`Meta registrada: ${x.meta}; campos gerais + específicas: ${x.attempted}.`,url:x.url});if(done(x.status)&&x.attempted>0&&x.acertos==null)out.push({severity:'medium',pe:x.pe,title:'Dia concluído sem resultado',detail:`Meta de ${x.meta||x.attempted} questões, mas o campo Acertos não está preenchido.`,url:x.url});}return out;}
function groups(errors){const m=new Map();for(const e of errors){if(!m.has(e.subject))m.set(e.subject,{subject:e.subject,errors:0,recurrent:0,high_critical:0,flashcards:0,latest_date:'',patterns:new Map(),timeline:new Map()});const x=m.get(e.subject);x.errors++;if(e.recurrence>0)x.recurrent++;if(['alta','critica'].includes(norm(e.severity)))x.high_critical++;if(e.flashcard)x.flashcards++;if(e.date>x.latest_date)x.latest_date=e.date;if(e.date)x.timeline.set(e.date,(x.timeline.get(e.date)||0)+1);for(const p of e.patterns)x.patterns.set(p,(x.patterns.get(p)||0)+1);}return[...m.values()].sort((a,b)=>b.errors-a.errors||a.subject.localeCompare(b.subject));}
function recommendation(x,top){const list=top.slice(0,3).map(y=>y.pattern).join(', ')||'os erros mais recentes';if(x.errors>=20)return`Prioridade máxima: retome diariamente ${list} e use os ${x.flashcards} flashcards registrados como revisão ativa.`;if(x.errors>=10)return`Reforço semanal: concentre a revisão em ${list} e acompanhe a reincidência após cada PE.`;return`Manutenção dirigida: revise ${list} antes do próximo bloco relacionado.`;}
export function build(controls,errors,redactions,date,syncedAt){
  const cs=[...controls].sort(sortDate), completed=cs.filter(x=>done(x.status)), active=cs.filter(x=>started(x.status));
  const nums=cs.map(x=>Number((x.pe||'').replace(/\D/g,''))).filter(Number.isFinite), totalPE=Math.max(112,...nums,0);
  const questions=completed.reduce((s,x)=>s+(x.attempted||x.meta||0),0), results=completed.filter(x=>x.acertos!=null&&x.attempted>0), correct=results.reduce((s,x)=>s+x.acertos,0), resultQuestions=results.reduce((s,x)=>s+x.attempted,0);
  const q=quality(cs), g=groups(errors), pt=g.find(x=>norm(x.subject)==='portugues'), portShare=errors.length?round((pt?.errors||0)/errors.length*100,1):0;
  const valid=redactions.filter(x=>/^RD\d{2,3}$/i.test(x.rd)), corrected=valid.filter(x=>x.corrected).length, notStarted=Math.max(0,valid.length-corrected), weeks=round(weeksBetween(date,EXAM_DATE),1), perWeek=weeks?round(notStarted/weeks,1):notStarted;
  const days=Math.max(1,Math.ceil((new Date(`${EXAM_DATE}T12:00:00-03:00`)-new Date(`${date}T12:00:00-03:00`))/86400000)+1), remaining=Math.max(0,totalPE-completed.length), pending=q.filter(x=>x.title==='Dia concluído sem resultado').length;
  const alerts=[];if(pt)alerts.push({level:'critical',title:'Português concentra o maior risco',detail:`${pt.errors} de ${errors.length} erros catalogados (${portShare.toFixed(1)}%). Priorize os padrões mais recorrentes.`,action:'Abrir riscos',href:'/sedes-tdas-dashboard/riscos/?materia=Português'});if(pending)alerts.push({level:'warning',title:'Resultados pendentes afetam as médias',detail:`${pending} PE concluídos continuam sem Acertos preenchidos.`,action:'Abrir auditoria',href:'/sedes-tdas-dashboard/auditoria/#qualidade'});if(notStarted)alerts.push({level:'warning',title:'Ritmo discursivo precisa ser protegido',detail:`Restam ${notStarted} redações. Ritmo necessário: ${perWeek.toFixed(1)} por semana.`,action:'Abrir redações',href:'/sedes-tdas-dashboard/redacoes/'});
  const view=x=>x?({...x,errors:errors.filter(e=>e.origin===x.pe).length,accuracy:accuracy(x),quality_flags:[],layer:'Execução operacional — Notion'}):null;
  const today=cs.find(x=>x.date===date)||cs.find(x=>x.date>=date&&!done(x.status))||cs.at(-1), latest=[...completed].sort(sortDate).at(-1)||[...active].sort(sortDate).at(-1)||cs.at(-1);
  const home={meta:meta(date),metrics:{completed:completed.length,totalPE,questions,correct,accuracy:resultQuestions?round(correct/resultQuestions*100):0,errors:errors.length,redactions:valid.length,calendarDays:days,operationalDays:days},today:view(today),latest:view(latest),alerts,projections:[{label:'Ritmo de PE',value:`${round(remaining/days,2).toFixed(2)} PE/dia`,formula:`${remaining} PE não concluídos ÷ ${days} dias operacionais inclusivos`},{label:'Ritmo de redações',value:`${perWeek.toFixed(1)}/semana`,formula:`${notStarted} redações não iniciadas ÷ ${weeks.toFixed(1)} semanas`},{label:'Questões com resultado',value:resultQuestions.toLocaleString('pt-BR'),formula:'Soma das questões dos PE com campo Acertos preenchido'}]};
  const risks={meta:meta(date),summary:{total:errors.length,recurrent:errors.filter(x=>x.recurrence>0).length,high:errors.filter(x=>['alta','critica'].includes(norm(x.severity))).length,critical:errors.filter(x=>norm(x.severity)==='critica').length,portShare},subjects:g.map(x=>({subject:x.subject,errors:x.errors,recurrent:x.recurrent,high_critical:x.high_critical})),recent:[...errors].sort((a,b)=>String(b.date).localeCompare(String(a.date))||String(b.last_edited_time).localeCompare(String(a.last_edited_time))).slice(0,12).map(({origin,title,subject,severity,url})=>({origin,title,subject,severity,url})),quality:q,alerts};
  const subjects={meta:meta(date),subjects:g.map(x=>{const top=[...x.patterns.entries()].sort((a,b)=>b[1]-a[1]).slice(0,5).map(([pattern,count])=>({pattern,count}));return{subject:x.subject,slug:slugify(x.subject),errors:x.errors,recurrent:x.recurrent,high_critical:x.high_critical,flashcards:x.flashcards,latest_date:x.latest_date,top_patterns:top,timeline:[...x.timeline.entries()].sort((a,b)=>a[0].localeCompare(b[0])).map(([date,count])=>({date,count})),recommendation:recommendation(x,top)};})};
  const redactionsOut={meta:meta(date),summary:{valid:valid.length,corrected,notStarted,perWeek,weeksRemaining:weeks},redactions:[...valid].sort((a,b)=>a.rd.localeCompare(b.rd)).map(x=>({rd:x.rd,week:x.week,pe:x.pe,date:x.date,theme:x.theme,status:x.status,url:x.url,score:x.score})),notice:'Dados lidos diretamente do banco oficial do Notion. Status, diagnóstico e notas só são exibidos quando constam na fonte.'};
  const state={apiVersion:API_VERSION,snapshotDate:date,syncedAt,semanticHash:'',counts:{controls:controls.length,errors:errors.length,redactions:redactions.length},pageVersions:Object.fromEntries([...controls,...errors,...redactions].map(x=>[x.id,x.last_edited_time]))};
  return{home,risks,subjects,redactionsOut,state};
}
