import fs from 'node:fs/promises';
import path from 'node:path';
import {buildSourceContract} from './notion/source-contract.mjs';
import {enrichMentorErrors} from './notion/mentor-enrichment.mjs';
const ROOT=process.cwd(),VERSION='26.0',SYNC_TIMES=['00h50','06h50','12h50','18h50'];
const read=async(file,fallback=null)=>{try{return JSON.parse(await fs.readFile(path.join(ROOT,file),'utf8'))}catch{return fallback}};
const write=async(file,value)=>{const target=path.join(ROOT,file);await fs.mkdir(path.dirname(target),{recursive:true});await fs.writeFile(target,`${JSON.stringify(value)}\n`,'utf8')};
function normalizeVersion(value){if(Array.isArray(value))return value.map(normalizeVersion);if(!value||typeof value!=='object')return typeof value==='string'?value.replaceAll('v24.1','v26.0'):value;const out={};for(const[key,item]of Object.entries(value)){if(key==='version'||key==='schemaVersion')out[key]=VERSION;else if(key==='syncTimes')out[key]=SYNC_TIMES;else out[key]=normalizeVersion(item)}return out}
await enrichMentorErrors();
const overlay=normalizeVersion(await read('data/live-v24.json',{}));await write('data/live-v24.json',overlay);
const sourceContract=await buildSourceContract({enforce:process.env.ENFORCE_SOURCE_CONTRACT!=='false'});
const errorIndex=await read('data/error-questions/index.json',{}),subjectsData=await read('data/subjects.json',{}),totalPE=112,partCount=Math.max(1,Number(errorIndex.parts?.length||0));
for(let number=1;number<=totalPE;number++){const file=path.join(ROOT,'pe',String(number),'index.html');try{const html=await fs.readFile(file,'utf8');const updated=html.replaceAll('assets/enhance-v20.js?v=20','assets/enhance-v20.js?v=26.2');if(updated!==html)await fs.writeFile(file,updated,'utf8')}catch(error){if(error?.code!=='ENOENT')throw error}}
const subjectSlugs=(subjectsData.subjects||[]).map(item=>item.slug).filter(Boolean),fallbackSlugs=['portugues','assistencia-social','lc-840-2011','arquivologia','direito-administrativo','lei-7-484-2024','materiais-e-patrimonio','primeiros-socorros','lei-maria-da-penha','redacao','atualidades-df-ride-pdpm','compras-publicas-lei-14-133','direito-constitucional'],slugs=subjectSlugs.length?subjectSlugs:fallbackSlugs;
const sw=`const VERSION='tdas-v26-daily-${new Date().toISOString().slice(0,10).replaceAll('-','')}-notion-daily-content-phase1-100';
const BASE='/sedes-tdas-dashboard/';
const USER_CACHE_PREFIXES=['tdas-redactions-user-'];
const CORE_ROUTES=["","hoje/","evolucao/","edital/","mentor/","riscos/","agenda/","redacoes/","auditoria/","mais/","configuracoes/","dados-locais/","questoes-erros/","pe/","materias/","estudar/","resolver/","revisar/","caderno-erros/","desempenho/","fila-ia/","offline.html","manifest.webmanifest"];
const ASSETS=["assets/styles.css","assets/v20.css","assets/common.js","assets/home.js","assets/home-mobile.js","assets/tdas-mobile-ux.js","assets/tdas-mobile-ux.css","assets/tdas-pro-dashboard.css","assets/home-mobile-hotfix.css","assets/tdas-pro-modules.css","assets/tdas-pro-modules.js","assets/tdas-command-palette.css","assets/tdas-command-palette.js","assets/mentor.js","assets/mentor.css","assets/settings.js","assets/today.js","assets/evolution.js","assets/edital.js","assets/edital.css","assets/risks.js","assets/agenda.js","assets/redactions.js","assets/audit.js","assets/more.js","assets/pe.js","assets/subject.js","assets/subjects-index.js","assets/error-questions.js","assets/enhance-v20.js","assets/integration/daily-execution.js","assets/integration/daily-law.js","assets/integration/today-execution.js","assets/integration/daily-question-page.js","assets/integration/daily-progress.js","assets/integration/local-backup.js","assets/integration/daily-content.css","assets/integration/command-center.css","assets/integration/home-command-center.js","assets/integration/home-study-intelligence.js","assets/integration/study-state.js","assets/integration/study-analytics.js","assets/integration/audit-unlinked-errors.js","assets/integration/session-draft.js","assets/integration/module-dashboard.js","assets/integration/module-player.js","assets/integration/module-store.js","assets/integration/review-engine.js","assets/integration/module-reviews.js","assets/integration/module-error-book.js","assets/integration/module-performance.js","assets/integration/module-performance-v3.js","assets/integration/module-ai-queue.js","assets/integration/player-core.js","assets/integration/player.css","assets/integration/study-ux.js","assets/integration/mentor-engine.js","assets/integration/mentor-ux.js"];
const DATA=["data/home.json","data/today.json","data/evolution.json","data/risks.json","data/agenda.json","data/redactions.json","data/audit.json","data/more.json","data/subjects.json","data/source-contract.json","data/edital-status.json","data/sync-history.json","data/live.json","data/live-v23.json","data/live-v24.json","data/error-questions/index.json","data/integration/navigation.json","data/integration/question-catalog.json","data/integration/daily-execution.json","data/integration/daily-material.json"];
const ICONS=['icons/icon.svg','icons/maskable.svg','icons/icon-192.png','icons/icon-512.png'];
const SUBJECTS=${JSON.stringify(slugs)};
const PRECACHE=[...CORE_ROUTES.map(path=>BASE+path),...ASSETS.map(path=>BASE+path),...DATA.map(path=>BASE+path),...ICONS.map(path=>BASE+path),...Array.from({length:${totalPE}},(_,index)=>BASE+'pe/'+(index+1)+'/'),...SUBJECTS.map(slug=>BASE+'materias/'+slug+'/'),...Array.from({length:${partCount}},(_,index)=>BASE+'data/error-questions/part-'+String(index+1).padStart(2,'0')+'.json')];
const shouldPreserveCache=key=>key===VERSION||USER_CACHE_PREFIXES.some(prefix=>key.startsWith(prefix));
self.addEventListener('install',event=>event.waitUntil(caches.open(VERSION).then(cache=>cache.addAll(PRECACHE)).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>!shouldPreserveCache(key)).map(key=>caches.delete(key)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const url=new URL(event.request.url);if(url.origin!==location.origin)return;if(event.request.mode==='navigate'){event.respondWith(fetch(event.request).then(response=>{const copy=response.clone();caches.open(VERSION).then(cache=>cache.put(event.request,copy));return response}).catch(()=>caches.match(event.request).then(cached=>cached||caches.match(BASE+'offline.html'))));return}if(url.pathname.includes('/data/')){event.respondWith(fetch(event.request).then(response=>{const copy=response.clone();caches.open(VERSION).then(cache=>cache.put(event.request,copy));return response}).catch(()=>caches.match(event.request)));return}event.respondWith(caches.match(event.request).then(cached=>cached||fetch(event.request).then(response=>{const copy=response.clone();caches.open(VERSION).then(cache=>cache.put(event.request,copy));return response})))});`;
await fs.writeFile(path.join(ROOT,'sw.js'),sw,'utf8');
console.log(JSON.stringify({version:VERSION,mode:'notion-daily-content',phase:'adaptive-review',errorParts:partCount,subjects:slugs.length,totalPE,userCachesPreserved:true,sourceContract:sourceContract.status}));